[package]
name = "scraping"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsing = { path = "../parsing" }
reqwest = { version = "0.11.3", features = ["blocking"] }
urlencoding = "1.1.1"
